site_name: The Practice Circle
site_description: A network of people training attention, honesty, and compassion in ordinary life.
site_author: The Practice Circle
site_url: https://simondilhas.github.io/practice_circle

# Repository
repo_name: simondilhas/practice_circle
repo_url: https://github.com/simondilhas/practice_circle

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started.md
    - Manifesto: index.md
    - Charta: framework/CHARTA.md
    - Practice: practice/STANDING_0_INTRO.md
  - Framework:
    - Charta: framework/CHARTA.md
    - How We Change: framework/HOW_WE_CHANGE.md
    - Decision Meeting Protocol: framework/DECISION_MEETING_PROTOCOL.md
    - Inspirational Traditions: framework/INSPIRATIONAL_TRADITIONS.md
  - Practice:
    - Introduction: practice/STANDING_0_INTRO.md
    - 1. Foundation: practice/STANDING_1_FOUNDATION.md
    - 2. Stabilisation: practice/STANDING_2_STABILISATION.md
    - 3. Refinement: practice/STANDING_3_REFINEMENT.md
    - 4. Transition: practice/STANDING_4_TRANSITION.md
    - 5. Integration: practice/STANDING_5_INTEGRATION.md
    - Appendices:
      - Author Notes: practice/STANDING_APPENDIX_AUTHOR_NOTES.md
      - Buddhist Concepts: practice/STANDING_APPENDIX_BUDDHIST_CONCEPTS.md
      - Stoic Concepts: practice/STANDING_APPENDIX_STOIC_CONCEPTS.md
      - Taoist Concepts: practice/STANDING_APPENDIX_TAOIST_CONCEPTS.md
      - Yogic Concepts: practice/STANDING_APPENDIX_YOGIC_CONCEPTS.md
  - Facilitators:
    - Facilitator Guide: facilitator/FACILITATOR_GUIDE.md
    - Mentorship: facilitator/MENTORSHIIP.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/simondilhas/practice_circle