site_name: The Practice Circle
site_description: A network of people training attention, honesty, and compassion in ordinary life.
site_author: The Practice Circle
site_url: https://thepracticecircle.org

# Repository
repo_name: simondilhas/practice_circle
repo_url: https://github.com/simondilhas/practice_circle

# Configuration
theme:
  name: material
  logo: assets/images/fav.svg
  favicon: assets/images/fav.svg
  breadcrumbs: false
  custom_dir: overrides
  palette:
    # Light mode only
    - scheme: default
      primary: black
      accent: "#DC4D01"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
  - Manifesto: manifesto.md
  - Getting Started: getting-started.md
  - How-To Guides:
    - Overview: howto/index.md
    - Practice:
      - Overview: howto/practice/index.md
      - Standing Meditation:
        - Introduction: howto/practice/standing_meditation/0_intro.md
        - 1. Foundation: howto/practice/standing_meditation/1_foundation.md
        - 2. Stabilisation: howto/practice/standing_meditation/2_stabilisation.md
        - 3. Refinement: howto/practice/standing_meditation/3_refinement.md
        - 4. Transition: howto/practice/standing_meditation/4_transition.md
        - 5. Integration: howto/practice/standing_meditation/5_integration.md
      - Practice Formats: howto/practice/practice_formats.md
      - Appendices:
        - Overview: howto/practice/standing_meditation/appendices/index.md
        - Author Notes: howto/practice/standing_meditation/appendices/author_notes.md
        - Buddhist Concepts: howto/practice/standing_meditation/appendices/buddhist_concepts.md
        - Stoic Concepts: howto/practice/standing_meditation/appendices/stoic_concepts.md
        - Taoist Concepts: howto/practice/standing_meditation/appendices/taoist_concepts.md
        - Yogic Concepts: howto/practice/standing_meditation/appendices/yogic_concepts.md
    - Organize:
      - Overview: howto/organize/index.md
      - Circle Roles:
        - Facilitator: howto/organize/roles/facilitator.md
        - Scribe: howto/organize/roles/scribe.md
        - Treasurer: howto/organize/roles/treasurer.md
      - Circle Lifecycle:
        - Create a Circle: howto/organize/lifecycle/create_a_circle.md
        - Introduction Meeting Script: howto/organize/lifecycle/introduction_meeting.md
        - Evolve the Circle: howto/organize/lifecycle/evolve_the_circle.md
        - Document Practices: howto/organize/lifecycle/document_practices.md
      - Protocols:
        - How to Join: howto/organize/protocols/how_to_join.md
        - Make Decisions: howto/organize/protocols/make_decisions.md
        - Resolve Conflicts: howto/organize/protocols/resolve_conflicts.md
        - Mentor Members: howto/organize/protocols/mentor_members.md
        - Contribute Changes: howto/organize/protocols/contribute_changes.md
        - Use LLM Assistance: howto/organize/protocols/use_llm_assistance.md
        - LLM Custom Prompts: howto/organize/protocols/llm_custom_prompts.md
      - Financial Management:
        - Circle Finances: howto/organize/finances/circle_finances.md
  - Research:
    - Practice Methodology: research/PRACTICE_METHODOLOGY.md
    - Literature Review: research/LITERATURE_REVIEW.md
    - Inspirational Traditions: research/INSPIRATIONAL_TRADITIONS.md
  - Network:
    - Overview: network/index.md
    - Logo Design: network/logo_design.md
    - Outreach and Visibility Plan: network/outreach_and_visibility_plan.md
    - Federation Finances: network/federation_finances.md
  - AI Custodian (GPT): https://chatgpt.com/g/g-68ee597597708191b5875c2a705d7117-the-practice-circle
  - The Practice Circle App: https://practice-circle.softr.app/login


# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/simondilhas/practice_circle
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ThePracticeCircle
    - icon: fontawesome/solid/blog
      link: https://dilhas.substack.com/s/the-practice-circle
  generator: false

# Copyright/Footer
copyright: <a href="/imprint/">Imprint</a> · <a href="/privacy-notice/">Privacy Policy</a> · <a href="/disclaimer/">Liability Notice</a>
